const EXAM_DATA = {
  id: 'enem',
  name: 'ENEM',
  icon: '📚',
  examDate: null,
  dailyHours: 0,
  categories: [
    {
      name: 'Biologia',
      icon: '🧬',
      topics: [
        { id: 'bio-01', name: 'Ecologia', estHours: 4, weight: 10, recurrenceScore: 100,
          subtopics: ['Cadeias e teias alimentares', 'Níveis tróficos', 'Fluxo de energia', 'Relações ecológicas (interespecíficas e intraespecíficas)', 'Biomas brasileiros', 'Ciclos biogeoquímicos (carbono, nitrogênio, água)', 'Desequilíbrio ambiental e eutrofização', 'Bioacumulação e magnificação trófica'] },
        { id: 'bio-02', name: 'Ecologia Avançada', estHours: 3, weight: 7, recurrenceScore: 75,
          subtopics: ['Sucessão ecológica primária e secundária', 'Pirâmides ecológicas', 'Produtividade primária líquida e bruta', 'Nichos ecológicos e habitat', 'Biomas mundiais (tundra, taiga, savana)', 'Efeito estufa e aquecimento global', 'Camada de ozônio e chuva ácida'] },
        { id: 'bio-03', name: 'Evolução', estHours: 3, weight: 5, recurrenceScore: 52,
          subtopics: ['Teorias evolutivas (Lamarck, Darwin, Neodarwinismo)', 'Seleção natural e artificial', 'Evidências evolutivas (fósseis, anatomia, molecular)', 'Especiação (alopátrica, simpátrica)', 'Deriva genética e fluxo gênico', 'Adaptação e irradiação adaptativa'] },
        { id: 'bio-04', name: 'Impacto Ambiental', estHours: 2, weight: 4, recurrenceScore: 40,
          subtopics: ['Poluição atmosférica, hídrica e do solo', 'Desmatamento e perda de biodiversidade', 'Mudanças climáticas e COP30', 'Bioindicadores ambientais', 'Reciclagem e economia circular'] },
        { id: 'bio-05', name: 'Moléculas Orgânicas', estHours: 3, weight: 6, recurrenceScore: 60,
          subtopics: ['Carboidratos (mono, di, polissacarídeos)', 'Lipídios (óleos, gorduras, fosfolipídios)', 'Proteínas e aminoácidos', 'Enzimas e cinética enzimática', 'Vitaminas hidrossolúveis e lipossolúveis', 'Ácidos nucleicos (DNA e RNA)'] },
        { id: 'bio-06', name: 'Transporte de Moléculas', estHours: 2, weight: 4, recurrenceScore: 38,
          subtopics: ['Difusão simples e facilitada', 'Osmose e pressão osmótica', 'Transporte ativo (bomba de Na+/K+)', 'Endocitose e exocitose', 'Transporte em vegetais (seiva bruta e elaborada)'] },
        { id: 'bio-07', name: 'Citologia', estHours: 4, weight: 8, recurrenceScore: 82,
          subtopics: ['Célula procariótica vs eucariótica', 'Membrana plasmática (modelo mosaico fluido)', 'Organelas citoplasmáticas (funções)', 'Núcleo celular e nucléolo', 'Citoesqueleto e movimento celular', 'Parede celular e vacúolos', 'Célula animal vs vegetal'] },
        { id: 'bio-08', name: 'Energia Celular', estHours: 3, weight: 6, recurrenceScore: 55,
          subtopics: ['Respiração celular aeróbica (glicólise, ciclo de Krebs, cadeia respiratória)', 'Fermentação alcoólica e láctica', 'Fotossíntese (fases clara e escura)', 'Quimiossíntese', 'ATP e metabolismo energético'] },
        { id: 'bio-09', name: 'Origem da Vida', estHours: 2, weight: 3, recurrenceScore: 30,
          subtopics: ['Teorias (criacionismo, panspermia, evolução química)', 'Experimento de Miller-Urey', 'Coacervados e primeiras células', 'Eras geológicas e fósseis'] },
        { id: 'bio-10', name: 'Bactérias, Algas e Fungos', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Classificação e características (Reino Monera, Protista, Fungi)', 'Bactérias Gram-positivas e Gram-negativas', 'Importância ecológica e econômica', 'Doenças bacterianas (tétano, tuberculose, meningite)', 'Algas unicelulares e pluricelulares', 'Fungos (bolores, leveduras, cogumelos)'] },
        { id: 'bio-11', name: 'Filogenia e Botânica Introdutória', estHours: 2, weight: 3, recurrenceScore: 32,
          subtopics: ['Árvores filogenéticas', 'Classificação dos seres vivos (Reinos, Domínios)', 'Briófitas e pteridófitas', 'Características gerais das plantas'] },
        { id: 'bio-12', name: 'Morfologia e Reprodução de Plantas', estHours: 3, weight: 4, recurrenceScore: 42,
          subtopics: ['Gimnospermas e angiospermas', 'Flor, fruto e semente', 'Polinização e dispersão de sementes', 'Germinação e desenvolvimento vegetal', 'Hormônios vegetais (auxina, giberelina, etileno)'] },
        { id: 'bio-13', name: 'Transporte em Vegetais', estHours: 2, weight: 3, recurrenceScore: 28,
          subtopics: ['Transpiração e gutação', 'Teoria da coesão-tensão (seiva bruta)', 'Teoria do fluxo em massa (seiva elaborada)', 'Abertura e fechamento estomático'] },
        { id: 'bio-14', name: 'Invertebrados', estHours: 3, weight: 5, recurrenceScore: 45,
          subtopics: ['Poríferos e cnidários', 'Platelmintos, nematelmintos e anelídeos', 'Moluscos e artrópodes', 'Equinodermos', 'Sistemas corporais (digestório, circulatório, excretor)', 'Simetria e celoma'] },
        { id: 'bio-15', name: 'Parasitoses e Doenças Endêmicas', estHours: 4, weight: 9, recurrenceScore: 95,
          subtopics: ['Viroses (dengue, zika, chikungunya, covid-19, HIV)', 'Protozooses (malária, doença de Chagas, leishmaniose)', 'Bacterioses (tuberculose, hanseníase, sífilis)', 'Verminoses (esquistossomose, ascaridíase, ancilostomose)', 'Ciclos de transmissão (vetores, hospedeiros)', 'Prevenção e vacinação', 'Epidemiologia e saúde pública'] },
        { id: 'bio-16', name: 'Vertebrados', estHours: 3, weight: 4, recurrenceScore: 38,
          subtopics: ['Peixes ósseos e cartilaginosos', 'Anfíbios (adaptações terrestres)', 'Répteis (ovo amniótico, conquista terrestre)', 'Aves (adaptações ao voo)', 'Mamíferos (homeotermia, placenta)'] },
        { id: 'bio-17', name: 'Sistema Digestório, Endócrino e Excretor', estHours: 4, weight: 8, recurrenceScore: 85,
          subtopics: ['Sistema digestório (boca, estômago, intestinos, glândulas anexas)', 'Absorção de nutrientes', 'Sistema endócrino (hipófise, tireoide, pâncreas, adrenais)', 'Hormônios e feedback hormonal', 'Sistema excretor (rins, néfrons, formação da urina)', 'Equilíbrio hidrossalino'] },
        { id: 'bio-18', name: 'Sistema Reprodutor e Reprodução Humana', estHours: 3, weight: 6, recurrenceScore: 58,
          subtopics: ['Sistema genital masculino e feminino', 'Ciclo menstrual e ovulatório', 'Gametogênese (espermatogênese, ovogênese)', 'Fecundação e desenvolvimento embrionário', 'Métodos contraceptivos', 'ISTs e prevenção'] },
        { id: 'bio-19', name: 'Sistema Cardiorrespiratório e Sangue', estHours: 4, weight: 8, recurrenceScore: 88,
          subtopics: ['Coração (anatomia e ciclo cardíaco)', 'Circulação sistêmica e pulmonar', 'Vasos sanguíneos (artérias, veias, capilares)', 'Sistema respiratório (pulmões, alvéolos, hematose)', 'Transporte de gases (O2 e CO2)', 'Sangue (hemácias, leucócitos, plaquetas)', 'Grupos sanguíneos (ABO, Rh, transfusões)'] },
        { id: 'bio-20', name: 'Sistema Nervoso e Musculoesquelético', estHours: 4, weight: 7, recurrenceScore: 65,
          subtopics: ['Neurônios e sinapses', 'Sistema nervoso central e periférico', 'Sistema nervoso autônomo (simpático e parassimpático)', 'Sistema esquelético (ossos e articulações)', 'Sistema muscular (tipos de músculos)', 'Contração muscular (actina, miosina, ATP)'] },
        { id: 'bio-21', name: 'DNA e Dogma Central', estHours: 3, weight: 8, recurrenceScore: 90,
          subtopics: ['Estrutura do DNA (dupla hélice, nucleotídeos)', 'Replicação do DNA', 'Transcrição (RNA mensageiro)', 'Tradução (ribossomos, tRNA, código genético)', 'Mutação gênica e reparo do DNA', 'Tecnologia do DNA recombinante', 'PCR e eletroforese', 'Clonagem e transgênicos'] },
        { id: 'bio-22', name: 'Genética Mendeliana', estHours: 4, weight: 9, recurrenceScore: 92,
          subtopics: ['Leis de Mendel (1ª e 2ª)', 'Heredogramas e padrões de herança', 'Probabilidade genética', 'Dominância completa e recessividade', 'Cruzamento-teste e retrocruzamento', 'Alelos múltiplos (sistema ABO)', 'Herança dos grupos sanguíneos Rh'] },
        { id: 'bio-23', name: 'Hereditariedade', estHours: 3, weight: 6, recurrenceScore: 55,
          subtopics: ['Herança autossômica recessiva e dominante', 'Herança ligada ao sexo (X e Y)', 'Herança mitocondrial', 'Penetrância e expressividade', 'Herança poligênica', 'Epistasia e pleiotropia'] },
        { id: 'bio-24', name: 'Genética Avançada', estHours: 3, weight: 5, recurrenceScore: 48,
          subtopics: ['Linkage e mapas genéticos', 'Crossing-over e recombinação', 'Mutações cromossômicas (aneuploidias, translocações)', 'Síndromes genéticas (Down, Turner, Klinefelter)', 'Genética de populações (Hardy-Weinberg)'] },
        { id: 'bio-25', name: 'Vírus e Imunidade', estHours: 4, weight: 9, recurrenceScore: 96,
          subtopics: ['Vírus (estrutura, replicação, ciclos lítico e lisogênico)', 'Principais viroses humanas', 'Sistema imune inato e adaptativo', 'Imunidade humoral (anticorpos) e celular', 'Vacinação e soros', 'Imunização ativa e passiva', 'HIV e AIDS', 'Câncer e imunovigilância'] },
        { id: 'bio-26', name: 'Neoplasia e Farmacologia', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Células cancerosas e oncogenes', 'Tumor benigno vs maligno', 'Metástase', 'Quimioterapia e radioterapia', 'Ação de fármacos no organismo'] }
      ]
    },
    {
      name: 'Química',
      icon: '⚗️',
      topics: [
        { id: 'qui-01', name: 'Modelos Atômicos', estHours: 3, weight: 6, recurrenceScore: 55,
          subtopics: ['Modelo de Dalton', 'Modelo de Thomson (pudim de passas)', 'Modelo de Rutherford (núcleo atômico)', 'Modelo de Bohr (camadas eletrônicas)', 'Modelo quântico (orbitais, números quânticos)', 'Evolução dos modelos atômicos'] },
        { id: 'qui-02', name: 'Camadas Eletrônicas', estHours: 3, weight: 5, recurrenceScore: 48,
          subtopics: ['Distribuição eletrônica (diagrama de Pauling)', 'Níveis e subníveis de energia', 'Configuração eletrônica de íons', 'Números quânticos (principal, secundário, magnético, spin)', 'Orbitais atômicos (s, p, d, f)'] },
        { id: 'qui-03', name: 'Tabela Periódica', estHours: 3, weight: 7, recurrenceScore: 65,
          subtopics: ['Organização da tabela (períodos, grupos, famílias)', 'Propriedades periódicas (raio atômico, eletronegatividade, afinidade eletrônica)', 'Metais, ametais, semimetais e gases nobres', 'Elementos de transição', 'Raio iônico e potencial de ionização'] },
        { id: 'qui-04', name: 'Ligações Químicas', estHours: 4, weight: 8, recurrenceScore: 78,
          subtopics: ['Ligação iônica (transferência de elétrons)', 'Ligação covalente (compartilhamento)', 'Ligação metálica (mar de elétrons)', 'Geometria molecular (linear, angular, trigonal, tetraédrica)', 'Polaridade das moléculas', 'Forças intermoleculares (dipolo-dipolo, London, pontes de hidrogênio)'] },
        { id: 'qui-05', name: 'Forças Intermoleculares', estHours: 3, weight: 5, recurrenceScore: 52,
          subtopics: ['Dipolo induzido (London)', 'Dipolo-dipolo', 'Ligação de hidrogênio (pontes de H)', 'Comparação de intensidade', 'Solubilidade (polar dissolve polar)', 'Temperatura de fusão e ebulição'] },
        { id: 'qui-06', name: 'Misturas e Separação', estHours: 2, weight: 4, recurrenceScore: 38,
          subtopics: ['Tipos de misturas (homogênea, heterogênea)', 'Separação de misturas (destilação, filtração, decantação)', 'Cromatografia', 'Substância pura vs mistura'] },
        { id: 'qui-07', name: 'Fórmulas Químicas', estHours: 3, weight: 6, recurrenceScore: 50,
          subtopics: ['Fórmula molecular, empírica e estrutural', 'Cálculo de fórmula mínima', 'Composição percentual', 'Massa molar e número de mol', 'Cálculo de massa a partir da fórmula'] },
        { id: 'qui-08', name: 'Reações Químicas', estHours: 4, weight: 7, recurrenceScore: 72,
          subtopics: ['Síntese ou adição', 'Análise ou decomposição', 'Simples troca (deslocamento)', 'Dupla troca (metátese)', 'Reações de precipitação', 'Reações de neutralização', 'Balanceamento de equações', 'Reações de combustão'] },
        { id: 'qui-09', name: 'Ácidos e Bases', estHours: 3, weight: 8, recurrenceScore: 80,
          subtopics: ['Teoria de Arrhenius (ácidos, bases)', 'Teoria de Brønsted-Lowry', 'Teoria de Lewis', 'pH e pOH (escala, cálculo)', 'Indicadores ácido-base', 'Neutralização e formação de sais', 'Hidrólise de sais'] },
        { id: 'qui-10', name: 'Reações com Ácidos', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Ácidos fortes e fracos', 'Reações de ácidos com metais', 'Reações de ácidos com carbonatos', 'Reações de ácidos com bases', 'Óxidos ácidos e básicos'] },
        { id: 'qui-11', name: 'Sais e Óxidos', estHours: 3, weight: 6, recurrenceScore: 55,
          subtopics: ['Classificação de sais (solúveis, insolúveis)', 'Reações de obtenção de sais', 'Óxidos ácidos, básicos, anfóteros e neutros', 'Reações de óxidos com água', 'Poluição por óxidos (NOx, SOx, CO2)'] },
        { id: 'qui-12', name: 'Estequiometria', estHours: 4, weight: 8, recurrenceScore: 85,
          subtopics: ['Relações massa-massa, massa-mol, mol-mol', 'Cálculo de rendimento (real vs teórico)', 'Reagente limitante e excesso', 'Pureza de reagentes', 'Fórmulas com porcentagem', 'Cálculos estequiométricos com gases'] },
        { id: 'qui-13', name: 'Termoquímica', estHours: 4, weight: 6, recurrenceScore: 68,
          subtopics: ['Reações endotérmicas e exotérmicas', 'Entalpia (H) e variação de entalpia (ΔH)', 'Entalpia de formação, combustão, ligação', 'Lei de Hess (soma das entalpias)', 'Energia de ligação', 'Calorimetria e capacidade calorífica'] },
        { id: 'qui-14', name: 'Equilíbrio Químico', estHours: 4, weight: 7, recurrenceScore: 75,
          subtopics: ['Constante de equilíbrio (Kc, Kp)', 'Princípio de Le Chatelier', 'Deslocamento de equilíbrio (temperatura, pressão, concentração)', 'Equilíbrio iônico (Ka, Kb, Kw)', 'Solubilidade e Kps', 'Efeito do íon comum'] },
        { id: 'qui-15', name: 'Oxirredução', estHours: 3, weight: 6, recurrenceScore: 65,
          subtopics: ['Número de oxidação (NOX)', 'Oxidação e redução', 'Agente oxidante e redutor', 'Balanceamento por redox', 'Série de reatividade dos metais', 'Corrosão e proteção'] },
        { id: 'qui-16', name: 'Pilhas e Eletroquímica', estHours: 4, weight: 5, recurrenceScore: 78,
          subtopics: ['Pilha de Daniell (Zn-Cu)', 'Potencial padrão de redução (E°)', 'Força eletromotriz (ΔE)', 'Equação de Nernst', 'Pilhas comerciais (leclanché, alcalina, lítio)', 'Eletrólise ígnea e aquosa', 'Leis de Faraday'] },
        { id: 'qui-17', name: 'Química Orgânica (Introdução)', estHours: 4, weight: 9, recurrenceScore: 92,
          subtopics: ['Carbono (hibridação sp³, sp², sp)', 'Cadeias carbônicas (aberta, fechada, saturada, insaturada)', 'Classificação de carbonos (primário, secundário, terciário, quaternário)', 'Funções orgânicas (hidrocarbonetos, álcoois, ácidos carboxílicos, ésteres)', 'Propriedades físicas dos compostos orgânicos'] },
        { id: 'qui-18', name: 'Cadeias Orgânicas', estHours: 3, weight: 7, recurrenceScore: 70,
          subtopics: ['Nomenclatura IUPAC de hidrocarbonetos', 'Alcanos, alcenos, alcinos, alcadienos', 'Cicloalcanos e aromáticos (benzeno)', 'Radicais orgânicos', 'Nomenclatura de funções oxigenadas e nitrogenadas'] },
        { id: 'qui-19', name: 'Isomeria', estHours: 3, weight: 6, recurrenceScore: 62,
          subtopics: ['Isomeria plana (função, posição, cadeia, metameria, tautomeria)', 'Isomeria geométrica (cis-trans)', 'Isomeria óptica (quiralidade, enantiômeros, diastereoisômeros)', 'Carbono assimétrico', 'Luz polarizada e atividade óptica'] },
        { id: 'qui-20', name: 'Reações Orgânicas', estHours: 4, weight: 7, recurrenceScore: 85,
          subtopics: ['Reações de substituição (alcanos, aromáticos)', 'Reações de adição (alcenos, alcinos)', 'Reações de eliminação (desidratação, desidrogenação)', 'Reações de oxidação (álcool → aldeído → ácido)', 'Reações de esterificação', 'Reações de saponificação e hidrólise', 'Polímeros (adição e condensação)'] },
        { id: 'qui-21', name: 'Ciclos da Matéria', estHours: 2, weight: 4, recurrenceScore: 32,
          subtopics: ['Ciclo do carbono', 'Ciclo do nitrogênio (fixação, nitrificação, desnitrificação)', 'Ciclo do fósforo', 'Ciclo da água', 'Impactos humanos nos ciclos biogeoquímicos'] },
        { id: 'qui-22', name: 'Petróleo e Combustíveis', estHours: 2, weight: 3, recurrenceScore: 35,
          subtopics: ['Composição do petróleo', 'Destilação fracionada', 'Gasolina, diesel, querosene, GLP', 'Número de octanas', 'Biocombustíveis (etanol, biodiesel)', 'Impacto ambiental dos combustíveis fósseis'] },
        { id: 'qui-23', name: 'Poluição e Descarte de Materiais', estHours: 2, weight: 3, recurrenceScore: 38,
          subtopics: ['Poluição por plásticos e microplásticos', 'Chuva ácida', 'Efeito estufa e gases de efeito estufa', 'Tratamento de água e esgoto', 'Lixo eletrônico e logística reversa'] },
        { id: 'qui-24', name: 'Reações Nucleares', estHours: 2, weight: 3, recurrenceScore: 35,
          subtopics: ['Radioatividade (α, β, γ)', 'Decaimento radioativo e meia-vida', 'Fissão nuclear (usinas nucleares)', 'Fusão nuclear (energia solar)', 'Aplicações (medicina, datação por C-14)', 'Acidentes nucleares e segurança'] }
      ]
    },
    {
      name: 'Física',
      icon: '⚡',
      topics: [
        { id: 'fis-01', name: 'Eletricidade', estHours: 4, weight: 8, recurrenceScore: 82,
          subtopics: ['Carga elétrica e processos de eletrização', 'Força elétrica (Lei de Coulomb)', 'Campo elétrico (carga puntiforme, placas paralelas)', 'Potencial elétrico e diferença de potencial (ddp)', 'Trabalho da força elétrica', 'Corrente elétrica (contínua e alternada)'] },
        { id: 'fis-02', name: 'Potencial Elétrico', estHours: 3, weight: 6, recurrenceScore: 52,
          subtopics: ['Potencial elétrico gerado por cargas', 'Superfícies equipotenciais', 'Relação campo-potencial', 'Energia potencial elétrica', 'Capacitores e capacitância', 'Associação de capacitores'] },
        { id: 'fis-03', name: 'Eletrodinâmica Básica', estHours: 4, weight: 8, recurrenceScore: 90,
          subtopics: ['1ª Lei de Ohm (R = V/i)', '2ª Lei de Ohm (resistividade)', 'Potência elétrica (P = V·i, P = R·i²)', 'Energia elétrica (kWh)', 'Resistores e associações (série, paralelo, misto)', 'Curto-circuito e fusíveis', 'Amperímetro e voltímetro'] },
        { id: 'fis-04', name: 'Eletrodinâmica Avançada', estHours: 3, weight: 5, recurrenceScore: 45,
          subtopics: ['Geradores elétricos (fem, resistência interna)', 'Receptores elétricos (força contra-eletromotriz)', 'Lei de Kirchhoff (nós e malhas)', 'Circuitos RC (carga e descarga de capacitor)', 'Ponte de Wheatstone'] },
        { id: 'fis-05', name: 'Eletromagnetismo', estHours: 4, weight: 7, recurrenceScore: 75,
          subtopics: ['Campo magnético (ímãs, bússola, Terra)', 'Campo magnético de fio retilíneo (Lei de Ampère)', 'Força magnética sobre cargas (F = q·v·B)', 'Força magnética sobre condutores', 'Indução eletromagnética (Lei de Faraday)', 'Lei de Lenz', 'Transformadores e geradores'] },
        { id: 'fis-06', name: 'Óptica Básica', estHours: 3, weight: 7, recurrenceScore: 70,
          subtopics: ['Reflexão da luz (leis, espelhos planos e esféricos)', 'Refração da luz (índice de refração, Lei de Snell)', 'Lentes esféricas (convergentes, divergentes)', 'Formação de imagens (côncavas, convexas)', 'Olho humano e defeitos da visão (miopia, hipermetropia)'] },
        { id: 'fis-07', name: 'Fenômenos Ópticos', estHours: 3, weight: 5, recurrenceScore: 48,
          subtopics: ['Difração da luz', 'Interferência luminosa', 'Polarização da luz', 'Dispersão da luz (prisma, arco-íris)', 'Cor dos objetos (absorção e reflexão seletiva)', 'Fibra óptica'] },
        { id: 'fis-08', name: 'Óptica Avançada', estHours: 3, weight: 4, recurrenceScore: 35,
          subtopics: ['Instrumentos ópticos (microscópio, telescópio, luneta)', 'Equação de Gauss para lentes', 'Aumento linear transversal', 'Associação de lentes', 'Óptica da visão (acomodação, adaptação)'] },
        { id: 'fis-09', name: 'Ondulatória Básica', estHours: 3, weight: 6, recurrenceScore: 72,
          subtopics: ['Ondas mecânicas e eletromagnéticas', 'Transversais vs longitudinais', 'Comprimento de onda, frequência, amplitude, período', 'Velocidade de propagação (v = λ·f)', 'Fenômenos ondulatórios (reflexão, refração, difração)', 'Ressonância'] },
        { id: 'fis-10', name: 'Ondulatória Avançada e Acústica', estHours: 3, weight: 5, recurrenceScore: 55,
          subtopics: ['Batimento e interferência de ondas', 'Ondas estacionárias (harmônicos, nós e ventres)', 'Efeito Doppler (fontes sonoras e luminosas)', 'Acústica (altura, timbre, intensidade)', 'Poluição sonora e decibéis'] },
        { id: 'fis-11', name: 'Termologia', estHours: 3, weight: 6, recurrenceScore: 68,
          subtopics: ['Temperatura e equilíbrio térmico', 'Escalas termométricas (Celsius, Fahrenheit, Kelvin)', 'Conversão entre escalas', 'Calor sensível (Q = m·c·ΔT)', 'Calor latente (mudança de fase)', 'Capacidade térmica e calor específico'] },
        { id: 'fis-12', name: 'Dilatação Térmica', estHours: 2, weight: 4, recurrenceScore: 38,
          subtopics: ['Dilatação linear (ΔL = L₀·α·ΔT)', 'Dilatação superficial (β = 2α)', 'Dilatação volumétrica (γ = 3α)', 'Dilatação anômala da água', 'Comportamento dos gases com temperatura'] },
        { id: 'fis-13', name: 'Energia e Termodinâmica', estHours: 5, weight: 7, recurrenceScore: 88,
          subtopics: ['1ª Lei da Termodinâmica (conservação de energia)', '2ª Lei da Termodinâmica (entropia)', 'Ciclo de Carnot e máquinas térmicas', 'Transformações gasosas (isotérmica, isobárica, isocórica, adiabática)', 'Trabalho de um gás', 'Refrigeradores e bombas de calor', 'Potência térmica e rendimento'] },
        { id: 'fis-14', name: 'Estudo dos Gases', estHours: 3, weight: 5, recurrenceScore: 48,
          subtopics: ['Equação de Clapeyron (PV = nRT)', 'Leis dos gases (Boyle, Charles, Gay-Lussac)', 'Transformações gasosas em gráficos', 'Teoria cinética molecular', 'Gás ideal vs real', 'Mistura de gases'] },
        { id: 'fis-15', name: 'Cinemática', estHours: 4, weight: 8, recurrenceScore: 85,
          subtopics: ['Velocidade média e aceleração', 'Movimento uniforme (MU)', 'Movimento uniformemente variado (MUV)', 'Queda livre e lançamento vertical', 'Lançamento horizontal e oblíquo', 'Movimento circular uniforme (MCU)', 'Gráficos de posição, velocidade e aceleração'] },
        { id: 'fis-16', name: 'Quantidade de Movimento', estHours: 3, weight: 5, recurrenceScore: 50,
          subtopics: ['Momento linear (Q = m·v)', 'Impulso (I = F·Δt)', 'Teorema do impulso (I = ΔQ)', 'Conservação da quantidade de movimento', 'Colisões elásticas e inelásticas', 'Centro de massa'] },
        { id: 'fis-17', name: 'Dinâmica', estHours: 5, weight: 8, recurrenceScore: 92,
          subtopics: ['Leis de Newton (inércia, F = m·a, ação e reação)', 'Diagrama de corpo livre', 'Força peso, normal, tração, atrito', 'Força elástica (Lei de Hooke)', 'Plano inclinado', 'Sistema de blocos e roldanas', 'Trabalho e energia mecânica', 'Conservação da energia'] },
        { id: 'fis-18', name: 'Gravitação', estHours: 3, weight: 4, recurrenceScore: 38,
          subtopics: ['Lei da Gravitação Universal', 'Leis de Kepler (órbitas planetárias)', 'Campo gravitacional', 'Satélites e velocidades orbital/escape', 'Peso e aceleração da gravidade'] },
        { id: 'fis-19', name: 'Molas e Estática', estHours: 3, weight: 5, recurrenceScore: 45,
          subtopics: ['Lei de Hooke (F = k·x)', 'Associação de molas (série e paralelo)', 'Equilíbrio de ponto material', 'Equilíbrio de corpo extenso (torque)', 'Alavancas e máquinas simples', 'Centro de gravidade e equilíbrio'] },
        { id: 'fis-20', name: 'Hidrostática', estHours: 3, weight: 6, recurrenceScore: 62,
          subtopics: ['Densidade e massa específica', 'Pressão hidrostática (P = d·g·h)', 'Teorema de Stevin (vasos comunicantes)', 'Princípio de Pascal (prensa hidráulica)', 'Empuxo (Princípio de Arquimedes)', 'Flutuação e densidade relativa'] }
      ]
    },
    {
      name: 'Geografia',
      icon: '🌍',
      topics: [
        { id: 'geo-01', name: 'Cartografia', estHours: 3, weight: 5, recurrenceScore: 48,
          subtopics: ['Elementos do mapa (título, legenda, escala, orientação)', 'Escala cartográfica (numérica e gráfica)', 'Projeções cartográficas (cilíndrica, cônica, azimutal)', 'Coordenadas geográficas (latitude, longitude)', 'Fusos horários e linha internacional de data'] },
        { id: 'geo-02', name: 'Tectonismo', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Teoria da Deriva Continental (Wegener)', 'Tectônica de placas (convergentes, divergentes, transformantes)', 'Orogênese e epirogênese', 'Terremotos e tsunamis', 'Vulcanismo e hotspots'] },
        { id: 'geo-03', name: 'Estrutura Geológica e Rochas', estHours: 2, weight: 4, recurrenceScore: 32,
          subtopics: ['Estrutura da Terra (crosta, manto, núcleo)', 'Rochas magmáticas, sedimentares e metamórficas', 'Ciclo das rochas', 'Escudos cristalinos e bacias sedimentares', 'Recursos minerais do Brasil'] },
        { id: 'geo-04', name: 'Relevo Brasileiro', estHours: 3, weight: 5, recurrenceScore: 45,
          subtopics: ['Classificação do relevo brasileiro (planaltos, planícies, depressões)', 'Principais unidades de relevo', 'Intemperismo (físico, químico, biológico)', 'Erosão e sedimentação', 'Formação do solo'] },
        { id: 'geo-05', name: 'Clima Brasileiro', estHours: 3, weight: 6, recurrenceScore: 58,
          subtopics: ['Tipos climáticos do Brasil (equatorial, tropical, semiárido, subtropical)', 'Fatores climáticos (latitude, altitude, continentalidade, maritimidade)', 'Massas de ar no Brasil', 'El Niño e La Niña', 'Mudanças climáticas e impactos no Brasil'] },
        { id: 'geo-06', name: 'Massas de Ar e Correntes Marítimas', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Circulação geral da atmosfera', 'Massas de ar (equatorial, tropical, polar)', 'Frentes frias e quentes', 'Correntes marítimas (quentes e frias)', 'Influência no clima global'] },
        { id: 'geo-07', name: 'Geografia Mundial', estHours: 3, weight: 5, recurrenceScore: 48,
          subtopics: ['Distribuição da população mundial', 'Países desenvolvidos vs subdesenvolvidos', 'Regionalização do mundo (Norte-Sul, continentes)', 'Organizações internacionais (ONU, OMC, FMI, Banco Mundial)', 'Globalização e fluxos mundiais'] },
        { id: 'geo-08', name: 'Demografia', estHours: 3, weight: 7, recurrenceScore: 72,
          subtopics: ['Crescimento populacional (taxas de natalidade, mortalidade)', 'Transição demográfica', 'Estrutura etária (pirâmides populacionais)', 'Migrações internacionais e refugiados', 'Envelhecimento populacional', 'Urbanização e metropolização'] },
        { id: 'geo-09', name: 'Urbanização', estHours: 3, weight: 7, recurrenceScore: 68,
          subtopics: ['Processo de urbanização mundial e brasileira', 'Hierarquia urbana e redes de cidades', 'Metrópoles, megalópoles e cidades globais', 'Problemas urbanos (favelização, mobilidade, violência)', 'Plano diretor e estatuto da cidade', 'Direito à cidade'] },
        { id: 'geo-10', name: 'Agricultura Moderna', estHours: 3, weight: 5, recurrenceScore: 52,
          subtopics: ['Revolução Verde e mecanização agrícola', 'Agronegócio vs agricultura familiar', 'Agrotóxicos e transgênicos', 'Sustentabilidade na agricultura', 'Mercado de commodities (soja, milho, café)'] },
        { id: 'geo-11', name: 'Sistemas Agrários', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Agricultura intensiva e extensiva', 'Pecuária (corte, leite, confinamento)', 'Extrativismo vegetal e mineral', 'Reforma agrária e conflitos no campo', 'Movimentos sociais rurais (MST)'] },
        { id: 'geo-12', name: 'Impacto Ambiental', estHours: 3, weight: 6, recurrenceScore: 62,
          subtopics: ['Desmatamento na Amazônia e Cerrado', 'Queimadas e degradação florestal', 'Poluição dos oceanos (plásticos, vazamentos de petróleo)', 'Perda de biodiversidade', 'Mudanças climáticas e COP30', 'Licenciamento ambiental'] },
        { id: 'geo-13', name: 'Hidrografia Brasileira', estHours: 3, weight: 5, recurrenceScore: 45,
          subtopics: ['Bacias hidrográficas do Brasil (Amazônica, Paraná, São Francisco)', 'Aquíferos (Guarani, Alter do Chão)', 'Hidrelétricas no Brasil', 'Crise hídrica e gestão de recursos hídricos', 'Usos múltiplos da água'] },
        { id: 'geo-14', name: 'Preservação Ambiental', estHours: 3, weight: 6, recurrenceScore: 55,
          subtopics: ['Unidades de conservação (parques, reservas, APAs)', 'Código Florestal e APP', 'Desenvolvimento sustentável e ODS', 'Economia verde e créditos de carbono', 'Licenciamento e educação ambiental'] },
        { id: 'geo-15', name: 'ONU e Direitos Humanos', estHours: 3, weight: 6, recurrenceScore: 58,
          subtopics: ['Estrutura da ONU (Assembleia, Conselho de Segurança)', 'Declaração Universal dos Direitos Humanos', 'Corte Internacional de Justiça', 'Peacekeeping e missões de paz', 'Agências da ONU (UNICEF, UNESCO, OMS)'] },
        { id: 'geo-16', name: 'Conflitos do Oriente Médio', estHours: 3, weight: 7, recurrenceScore: 72,
          subtopics: ['Conflito Israel-Palestina (história, Gaza, Cisjordânia)', 'Guerra na Síria', 'Primavera Árabe e consequências', 'Petróleo e geopolítica do Oriente Médio', 'Irã e programa nuclear', 'Fundamentalismo islâmico'] },
        { id: 'geo-17', name: 'Conceitos de Sociologia', estHours: 2, weight: 5, recurrenceScore: 45,
          subtopics: ['Durkheim (fatos sociais, solidariedade)', 'Marx (luta de classes, alienação, mais-valia)', 'Weber (ação social, burocracia)', 'Estratificação social', 'Mobilidade social'] },
        { id: 'geo-18', name: 'Segregação Racial e Lutas Sociais', estHours: 3, weight: 7, recurrenceScore: 75,
          subtopics: ['Racismo estrutural e institucional', 'Movimento negro no Brasil', 'Movimentos feministas e igualdade de gênero', 'Movimento LGBTQIA+', 'Movimentos indígenas e demarcação de terras', 'Ações afirmativas (cotas)'] },
        { id: 'geo-19', name: 'Questões de Gênero', estHours: 2, weight: 5, recurrenceScore: 48,
          subtopics: ['Gênero e sexualidade', 'Desigualdade de gênero no mercado de trabalho', 'Violência de gênero (feminicídio)', 'Políticas públicas para mulheres', 'Interseccionalidade'] },
        { id: 'geo-20', name: 'Globalização e Trabalho', estHours: 3, weight: 6, recurrenceScore: 65,
          subtopics: ['Globalização econômica e cultural', 'Precarização do trabalho (uberização, informalidade)', 'Desemprego estrutural', 'Terceirização e reforma trabalhista', 'Cadeias globais de valor', 'Comércio justo'] },
        { id: 'geo-21', name: 'Tecnologia e Sociedade', estHours: 2, weight: 4, recurrenceScore: 42,
          subtopics: ['Revolução 4.0 e Indústria 4.0', 'Inteligência Artificial e automação', 'Redes sociais e cibercultura', 'Inclusão digital e desigualdade tecnológica', 'Privacidade e proteção de dados (LGPD)'] },
        { id: 'geo-22', name: 'Pós-Modernidade', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Características da pós-modernidade', 'Sociedade do consumo e do espetáculo', 'Identidade e cultura na globalização', 'Crise das grandes narrativas', 'Multiculturalismo'] },
        { id: 'geo-23', name: 'Indústria Cultural', estHours: 2, weight: 4, recurrenceScore: 38,
          subtopics: ['Escola de Frankfurt (Adorno, Horkheimer)', 'Mass media e cultura de massa', 'Indústria do entretenimento', 'Manipulação e alienação cultural', 'Cultura erudita vs popular'] },
        { id: 'geo-24', name: 'Modelos de Produção', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Fordismo (produção em massa)', 'Taylorismo (divisão do trabalho)', 'Toyotismo (just-in-time, flexibilização)', 'Volvismo (produção modular)', 'Pós-fordismo'] },
        { id: 'geo-25', name: 'Economia Mundial', estHours: 3, weight: 6, recurrenceScore: 58,
          subtopics: ['Crise de 2008 e recuperação', 'Ascensão da China e guerra comercial EUA-China', 'BRICS e nova ordem econômica', 'Globalização financeira', 'Protecionismo vs livre comércio', 'Criptomoedas e blockchain'] },
        { id: 'geo-26', name: 'Blocos Econômicos', estHours: 3, weight: 5, recurrenceScore: 50,
          subtopics: ['UE (União Europeia)', 'Mercosul e ALCA', 'USMCA (antigo NAFTA)', 'UNASUL e Integração Sul-Americana', 'Zona do Euro e crises europeias', 'Brexit'] }
      ]
    },
    {
      name: 'Linguagens',
      icon: '📝',
      topics: [
        { id: 'lin-01', name: 'Funções da Linguagem', estHours: 3, weight: 7, recurrenceScore: 72,
          subtopics: ['Função referencial (denotativa)', 'Função emotiva (expressiva)', 'Função conativa (apelativa)', 'Função fática', 'Função metalinguística', 'Função poética', 'Análise de textos multimodais'] },
        { id: 'lin-02', name: 'Gêneros e Tipos Textuais', estHours: 3, weight: 8, recurrenceScore: 90,
          subtopics: ['Narração (elementos, estrutura, foco narrativo)', 'Descrição (objetiva e subjetiva)', 'Dissertação (argumentativa e expositiva)', 'Injunção (texto instrucional)', 'Gêneros textuais (artigo, crônica, reportagem, carta)', 'Suportes e esferas de circulação'] },
        { id: 'lin-03', name: 'Linguística Histórica', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Formação do português brasileiro', 'Influências indígenas, africanas e imigrantes', 'Deriva e mudança linguística', 'Fonética e fonologia histórica'] },
        { id: 'lin-04', name: 'Variantes Linguísticas', estHours: 2, weight: 5, recurrenceScore: 68,
          subtopics: ['Variação geográfica (regionalismos)', 'Variação social (gírias, jargões)', 'Variação situacional (formal vs informal)', 'Variação histórica (arcaísmos)', 'Preconceito linguístico', 'Norma culta vs coloquial'] },
        { id: 'lin-05', name: 'Linguagem Formal e Informal', estHours: 2, weight: 4, recurrenceScore: 42,
          subtopics: ['Registros de linguagem', 'Adequação comunicativa', 'Marcas de oralidade na escrita', 'Gírias e expressões idiomáticas', 'Níveis de formalidade'] },
        { id: 'lin-06', name: 'Argumentação e Discurso', estHours: 3, weight: 7, recurrenceScore: 78,
          subtopics: ['Estratégias argumentativas (dados, exemplos, citações)', 'Operadores argumentativos (conjunções, preposições)', 'Progressão temática e coesão', 'Tese, antítese e síntese', 'Falácias lógicas e argumentação válida'] },
        { id: 'lin-07', name: 'Recursos Expressivos', estHours: 2, weight: 5, recurrenceScore: 48,
          subtopics: ['Coesão referencial (anáfora, catáfora)', 'Coesão sequencial', 'Coerência textual', 'Intertextualidade (explícita, implícita)', 'Paródia, paráfrase e citação'] },
        { id: 'lin-08', name: 'Figuras de Linguagem', estHours: 3, weight: 7, recurrenceScore: 75,
          subtopics: ['Metáfora e metonímia', 'Comparação e analogia', 'Antítese e paradoxo', 'Hipérbole e eufemismo', 'Ironia e humor', 'Personificação (prosopopeia)', 'Aliteração e assonância', 'Pleonasmo e elipse'] },
        { id: 'lin-09', name: 'Seleção Lexical', estHours: 2, weight: 4, recurrenceScore: 38,
          subtopics: ['Denotação e conotação', 'Polissemia e ambiguidade', 'Campos semânticos', 'Neologismos e estrangeirismos', 'Homonímia e paronímia'] },
        { id: 'lin-10', name: 'Texto Literário e Utilitário', estHours: 2, weight: 5, recurrenceScore: 45,
          subtopics: ['Literariedade e função estética', 'Texto utilitário (função prática)', 'Gêneros literários (lírico, épico, dramático)', 'Suportes midiáticos contemporâneos'] },
        { id: 'lin-11', name: 'Verbos e Modos', estHours: 3, weight: 5, recurrenceScore: 52,
          subtopics: ['Modos verbais (indicativo, subjuntivo, imperativo)', 'Tempos verbais (presente, pretérito, futuro)', 'Locuções verbais e verbos auxiliares', 'Formas nominais (infinitivo, gerúndio, particípio)', 'Correlação temporal'] },
        { id: 'lin-12', name: 'Concordância Verbal e Nominal', estHours: 3, weight: 6, recurrenceScore: 62,
          subtopics: ['Regra geral de concordância verbal', 'Casos especiais (sujeito coletivo, porcentagem, aposto)', 'Concordância nominal (artigo, adjetivo, numeral)', 'Casos especiais (anexo, obrigado, mesmo, próprio)'] },
        { id: 'lin-13', name: 'Sintaxe', estHours: 3, weight: 6, recurrenceScore: 58,
          subtopics: ['Sujeito (simples, composto, oculto, indeterminado, oração sem sujeito)', 'Predicado (verbal, nominal, verbo-nominal)', 'Complementos (objeto direto, indireto, agente da passiva)', 'Adjuntos (adnominal, adverbial)', 'Orações coordenadas e subordinadas'] },
        { id: 'lin-14', name: 'Análise de Poemas', estHours: 3, weight: 6, recurrenceScore: 60,
          subtopics: ['Métrica e ritmo (sílabas poéticas)', 'Rimas (consoantes, toantes, ricas, pobres)', 'Estrofes (soneto, quadra, terceto)', 'Figuras de som e sentido', 'Eu lírico e tom do poema', 'Interpretação de poemas'] },
        { id: 'lin-15', name: 'Romantismo e Realismo', estHours: 3, weight: 7, recurrenceScore: 72,
          subtopics: ['Romantismo no Brasil (Indianismo, Ultrarromantismo, Condoreirismo)', 'Principais autores (Gonçalves Dias, José de Alencar, Castro Alves)', 'Realismo e Naturalismo (Machado de Assis, Aluísio Azevedo)', 'Características estéticas de cada escola'] },
        { id: 'lin-16', name: 'Vanguardas e Pré-Modernismo', estHours: 2, weight: 4, recurrenceScore: 40,
          subtopics: ['Vanguardas europeias (Expressionismo, Cubismo, Futurismo, Dadaísmo, Surrealismo)', 'Semana de Arte Moderna de 1922', 'Pré-Modernismo (Euclides da Cunha, Lima Barreto, Monteiro Lobato)', 'Contexto histórico-cultural'] },
        { id: 'lin-17', name: 'Modernismo Brasileiro', estHours: 3, weight: 6, recurrenceScore: 65,
          subtopics: ['1ª fase (Oswald de Andrade, Mário de Andrade, Manuel Bandeira)', '2ª fase (Carlos Drummond, Cecília Meireles, Vinicius de Moraes)', '3ª fase (João Cabral, Guimarães Rosa, Clarice Lispector)', 'Concretismo e poesia contemporânea'] },
        { id: 'lin-18', name: 'Arte Brasileira', estHours: 2, weight: 4, recurrenceScore: 38,
          subtopics: ['Arte colonial (Aleijadinho, Missão Artística Francesa)', 'Arte moderna (Tarsila, Portinari, Di Cavalcanti)', 'Arte contemporânea e instalações', 'Música popular brasileira', 'Cinema e teatro nacionais'] },
        { id: 'lin-19', name: 'Mídia e Tecnologia', estHours: 2, weight: 4, recurrenceScore: 42,
          subtopics: ['Linguagem digital (hipertexto, hiperlink)', 'Redes sociais e comunicação instantânea', 'Fake news e desinformação', 'Curadoria de informação', 'Multiletramentos'] },
        { id: 'lin-20', name: 'Direitos Humanos na Literatura', estHours: 2, weight: 5, recurrenceScore: 52,
          subtopics: ['Literatura de testemunho', 'Memorialismo e ditadura militar', 'Literatura periférica e marginal', 'Representatividade e diversidade', 'Literatura indígena e afro-brasileira'] },
        { id: 'lin-21', name: 'Preconceito e Violência', estHours: 2, weight: 5, recurrenceScore: 48,
          subtopics: ['Violência de gênero na literatura e mídia', 'Racismo e representação midiática', 'Violência simbólica', 'Discurso de ódio e regulação', 'Mídia e construção de estereótipos'] },
        { id: 'lin-22', name: 'Educação Física e Saúde', estHours: 2, weight: 3, recurrenceScore: 28,
          subtopics: ['Esporte e sociedade', 'Corpo e cultura', 'Sedentarismo e qualidade de vida', 'Esportes radicais e alternativos', 'Jogos olímpicos e paraolímpicos'] },
        { id: 'lin-23', name: 'Interpretação de Textos', estHours: 3, weight: 7, recurrenceScore: 95,
          subtopics: ['Leitura e compreensão crítica', 'Informações implícitas (inferências, pressupostos, subentendidos)', 'Intencionalidade do autor', 'Interdiscursividade', 'Análise de charges, tirinhas e cartoons', 'Interpretação de gráficos e infográficos'] }
      ]
    },
    {
      name: 'História',
      icon: '🏛️',
      topics: [
        { id: 'his-01', name: 'Antiguidade Oriental', estHours: 2, weight: 3, recurrenceScore: 25,
          subtopics: ['Mesopotâmia (sumérios, acádios, babilônios)', 'Egito Antigo (sociedade, religião, faraós)', 'Hebreus, fenícios e persas', 'Modo de produção asiático'] },
        { id: 'his-02', name: 'Mundo Grego', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Civilização cretense e micênica', 'Pólis grega (Atenas e Esparta)', 'Democracia ateniense', 'Guerras Médicas e Guerra do Peloponeso', 'Período Helenístico (Alexandre, Império)'] },
        { id: 'his-03', name: 'Surgimento da Filosofia', estHours: 2, weight: 3, recurrenceScore: 30,
          subtopics: ['Pré-socráticos (Tales, Pitágoras, Heráclito, Parmênides)', 'Sócrates e o método socrático', 'Platão (mundo das ideias, alegoria da caverna)', 'Aristóteles (lógica, ética, política)'] },
        { id: 'his-04', name: 'Império Romano', estHours: 2, weight: 4, recurrenceScore: 38,
          subtopics: ['República Romana (patrícios, plebeus, conflitos)', 'Expansão territorial e crise da República', 'Império (Pax Romana, Augusto)', 'Crise do Império e invasões bárbaras', 'Legado romano (direito, língua, estradas)'] },
        { id: 'his-05', name: 'Origens do Direito e Democracia', estHours: 2, weight: 4, recurrenceScore: 32,
          subtopics: ['Direito romano (Lei das XII Tábuas, Corpus Juris Civilis)', 'Democracia ateniense vs democracia moderna', 'Cidadania na Antiguidade', 'Conceitos de justiça (Aristóteles, Cícero)'] },
        { id: 'his-06', name: 'Ascensão do Feudalismo', estHours: 2, weight: 3, recurrenceScore: 28,
          subtopics: ['Formação do feudalismo (fusão romano-germânica)', 'Relações de suserania e vassalagem', 'Igreja medieval e poder', 'Economia feudal (autossuficiência, servidão)'] },
        { id: 'his-07', name: 'Queda do Feudalismo', estHours: 2, weight: 3, recurrenceScore: 30,
          subtopics: ['Crescimento comercial e feiras medievais', 'Renascimento urbano', 'Crise do século XIV (peste, fome, guerra)', 'Revoltas camponesas', 'Formação dos Estados Nacionais'] },
        { id: 'his-08', name: 'Revolução Científica', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Copérnico e Galileu (heliocentrismo)', 'Newton (mecânica, gravitação universal)', 'Método científico (Bacon, Descartes)', 'Conflito ciência vs igreja', 'Iluminismo (Rousseau, Voltaire, Montesquieu)'] },
        { id: 'his-09', name: 'América Pré-Colombiana', estHours: 2, weight: 4, recurrenceScore: 32,
          subtopics: ['Maias (calendário, escrita)', 'Astecas (Império, Tenochtitlán)', 'Incas (Império, estradas, Machu Picchu)', 'Sociedades indígenas brasileiras (Tupi, Guarani)', 'Conquista espanhola (Cortez, Pizarro)'] },
        { id: 'his-10', name: 'Escravidão e Pacto Colonial', estHours: 3, weight: 8, recurrenceScore: 88,
          subtopics: ['Escravidão indígena e africana', 'Tráfico negreiro e diáspora africana', 'Pacto Colonial (monopólio, exclusivo metropolitano)', 'Sociedade colonial brasileira (senhores, escravos, livres)', 'Quilombos e resistência negra (Palmares)', 'Economia colonial (açúcar, ouro, pecuária)'] },
        { id: 'his-11', name: 'Ciclos Econômicos Brasileiros', estHours: 3, weight: 6, recurrenceScore: 62,
          subtopics: ['Ciclo do Pau-Brasil', 'Ciclo do Açúcar (engenhos, sociedade açucareira)', 'Ciclo do Ouro (Minas Gerais, sociedade mineradora)', 'Ciclo do Café (Vale do Paraíba, Oeste Paulista)', 'Borracha e outros ciclos regionais'] },
        { id: 'his-12', name: 'Contratualismo e Estados Modernos', estHours: 2, weight: 4, recurrenceScore: 35,
          subtopics: ['Hobbes (estado de natureza, Leviatã)', 'Locke (direitos naturais, propriedade)', 'Rousseau (vontade geral, contrato social)', 'Formação do Estado Moderno (absolutismo)', 'Maquiavel e a razão de Estado'] },
        { id: 'his-13', name: 'Antigo Regime e Iluminismo', estHours: 3, weight: 5, recurrenceScore: 52,
          subtopics: ['Absolutismo monárquico (Luís XIV, Versailles)', 'Sociedade estamental (clero, nobreza, povo)', 'Iluminismo e Enciclopédia', 'Despotismo Esclarecido (Pombal, Frederico II)', 'Fisiocracia e liberalismo econômico'] },
        { id: 'his-14', name: 'Revolução Francesa', estHours: 3, weight: 6, recurrenceScore: 65,
          subtopics: ['Causas (crise financeira, desigualdade, iluminismo)', 'Queda da Bastilha e Assembleia Nacional', 'Fases (Girondinos, Jacobinos, Diretório)', 'Napoleão Bonaparte (Código Napoleônico, guerras)', 'Legado (liberalismo, nacionalismo)'] },
        { id: 'his-15', name: 'Revolução Industrial', estHours: 3, weight: 7, recurrenceScore: 75,
          subtopics: ['1ª Revolução Industrial (máquina a vapor, carvão)', '2ª Revolução Industrial (eletricidade, aço, petróleo)', 'Urbanação e condições de trabalho', 'Movimento operário (ludismo, cartismo, sindicatos)', 'Marx e o socialismo científico', '3ª Revolução Industrial (informática, automação)'] },
        { id: 'his-16', name: 'Kant e Nietzsche', estHours: 2, weight: 3, recurrenceScore: 25,
          subtopics: ['Kant (imperativo categórico, esclarecimento)', 'Nietzsche (vontade de potência, super-homem)', 'Crítica à moral e à metafísica', 'Niilismo e transvaloração dos valores'] },
        { id: 'his-17', name: 'Brasil Imperial', estHours: 3, weight: 7, recurrenceScore: 78,
          subtopics: ['Independência do Brasil (1822, processo, crises)', '1º Reinado (D. Pedro I, Constituição 1824, Confederação do Equador)', 'Período Regencial (Cabanagem, Farroupilha, Sabinada)', '2º Reinado (D. Pedro II, café, ferrovias)', 'Abolição da Escravatura (Lei Áurea, Lei do Ventre Livre)', 'Guerra do Paraguai e crise do Império'] },
        { id: 'his-18', name: 'República Velha', estHours: 3, weight: 6, recurrenceScore: 68,
          subtopics: ['Proclamação da República (1889)', 'República da Espada (Deodoro, Floriano)', 'Política do Café-com-Leite e Coronelismo', 'Política dos Governadores', 'Revoltas (Canudos, Contestado, Vacina, Chibata)', 'Crise de 1929 e Revolução de 1930'] },
        { id: 'his-19', name: 'Revoltas Brasileiras', estHours: 3, weight: 5, recurrenceScore: 48,
          subtopics: ['Inconfidência Mineira (1789)', 'Conjuração Baiana (1798)', 'Balaiada e Cabanagem', 'Revolta Farroupilha', 'Revolta da Chibata', 'Coluna Prestes'] },
        { id: 'his-20', name: 'Imperialismo e Neocolonialismo', estHours: 3, weight: 5, recurrenceScore: 55,
          subtopics: ['Conferência de Berlim (1885)', 'Partilha da África e Ásia', 'Neocolonialismo (matérias-primas, mercado)', 'Missão civilizadora e darwinismo social', 'Resistência anticolonial (Índia, Gandhi)'] },
        { id: 'his-21', name: 'EUA e Rússia', estHours: 2, weight: 4, recurrenceScore: 38,
          subtopics: ['Formação dos EUA (independência, Guerra Civil, Constituição)', 'Doutrina Monroe e expansionismo', 'Revolução Russa (1917, Lênin, Stalin)', 'URSS (comunismo, planos quinquenais, stalinismo)'] },
        { id: 'his-22', name: 'Era Vargas', estHours: 3, weight: 7, recurrenceScore: 75,
          subtopics: ['Governo Provisório (1930-1934)', 'Constituição de 1934 e Estado Novo (1937-1945)', 'Legislação trabalhista (CLT, salário mínimo)', 'Industrialização brasileira e substituição de importações', 'Segunda Guerra e entrada do Brasil', 'Queda de Vargas'] },
        { id: 'his-23', name: 'Industrialização Brasileira', estHours: 3, weight: 5, recurrenceScore: 48,
          subtopics: ['Industrialização restringida (anos 30-50)', 'JK e Plano de Metas (50 anos em 5)', 'Milagre Econômico (1968-1973)', 'Crise da dívida e década perdida (1980)', 'Neoliberalismo e privatizações (anos 90)'] },
        { id: 'his-24', name: 'Totalitarismo e 2ª Guerra', estHours: 3, weight: 7, recurrenceScore: 72,
          subtopics: ['Fascismo italiano (Mussolini)', 'Nazismo alemão (Hitler, Holocausto)', 'Stalinismo (URSS, expurgos, gulags)', 'Espanha franquista e salazarismo', '2ª Guerra Mundial (causas, eventos, consequências)', 'Bomba atômica e guerra fria inicial'] },
        { id: 'his-25', name: 'Guerra Fria', estHours: 3, weight: 6, recurrenceScore: 65,
          subtopics: ['Divisão do mundo (OTAN, Pacto de Varsóvia)', 'Corrida armamentista e nuclear', 'Guerra da Coreia e Vietnã', 'Crise dos Mísseis (Cuba, 1962)', 'Queda do Muro de Berlim (1989)', 'Fim da URSS (1991)'] },
        { id: 'his-26', name: 'República Populista (1945-1964)', estHours: 2, weight: 4, recurrenceScore: 42,
          subtopics: ['Governo Dutra (Constituição de 1946)', '2º Governo Vargas (1951-1954)', 'Governo Juscelino Kubitschek', 'Governo Jânio Quadros e João Goulart', 'Crise política e Reformas de Base'] },
        { id: 'his-27', name: 'Ditadura e Nova República', estHours: 3, weight: 6, recurrenceScore: 72,
          subtopics: ['Golpe de 1964 e AI-1', 'Atos Institucionais (AI-5, repressão)', 'Milagre Econômico e censura', 'Luta armada e resistência democrática', 'Abertura (1979-1985, Anistia, Diretas Já)', 'Constituição de 1988 (Constituição Cidadã)', 'Governos Collor, FHC, Lula, Dilma, Temer, Lula 2'] },
        { id: 'his-28', name: 'Constituições Brasileiras', estHours: 2, weight: 5, recurrenceScore: 45,
          subtopics: ['Constituição de 1824 (Poder Moderador)', 'Constituição de 1891 (federalismo, voto aberto)', 'Constituição de 1934 (direitos sociais)', 'Constituição de 1937 (Polaca, autoritária)', 'Constituição de 1946 (democrática)', 'Constituição de 1967 e EC 1969', 'Constituição de 1988 (direitos, estado democrático)'] }
      ]
    },
    {
      name: 'Matemática',
      icon: '📐',
      topics: [
        { id: 'mat-01', name: 'Matemática Básica', estHours: 3, weight: 8, recurrenceScore: 82,
          subtopics: ['Operações fundamentais (adição, subtração, divisão, multiplicação)', 'Frações (equivalentes, operações)', 'Números decimais e dízimas', 'Potenciação e radiciação', 'Expressões numéricas', 'MMC e MDC'] },
        { id: 'mat-02', name: 'Potenciação', estHours: 2, weight: 5, recurrenceScore: 48,
          subtopics: ['Propriedades das potências', 'Potência de 10 e notação científica', 'Radiciação (raiz quadrada, cúbica)', 'Racionalização de denominadores', 'Operações com radicais'] },
        { id: 'mat-03', name: 'Porcentagem', estHours: 3, weight: 9, recurrenceScore: 98,
          subtopics: ['Cálculo de porcentagem (regra de três)', 'Aumento e desconto percentual', 'Lucro e prejuízo percentual', 'Juros simples e compostos', 'Inflação e correção monetária', 'Taxas e índices econômicos'] },
        { id: 'mat-04', name: 'Razão e Matemática Financeira', estHours: 3, weight: 7, recurrenceScore: 75,
          subtopics: ['Razão e proporção', 'Escalas e mapas', 'Divisão proporcional', 'Regra de três simples e composta', 'Juros compostos (M = C·(1+i)^t)', 'Sistema de amortização'] },
        { id: 'mat-05', name: 'Equação de 1º Grau', estHours: 2, weight: 6, recurrenceScore: 52,
          subtopics: ['Resolução de equações lineares', 'Inequações do 1º grau', 'Função afim (f(x) = ax + b, gráfico, taxa de variação)', 'Sistemas de equações (substituição, adição)'] },
        { id: 'mat-06', name: 'Sistemas e Vazão', estHours: 3, weight: 5, recurrenceScore: 48,
          subtopics: ['Sistemas de equações lineares (2x2, 3x3)', 'Problemas de torneiras e vazão', 'Misturas e soluções', 'Tempo de trabalho conjunto', 'Equivalência de sistemas'] },
        { id: 'mat-07', name: 'Estatística', estHours: 4, weight: 8, recurrenceScore: 95,
          subtopics: ['Média aritmética simples e ponderada', 'Mediana e moda', 'Variância e desvio padrão', 'Amplitude e quartis', 'Histogramas e polígono de frequências', 'Interpretação de tabelas e gráficos (pizza, barras, linhas)', 'Box-plot e distribuição de dados'] },
        { id: 'mat-08', name: 'Progressões', estHours: 3, weight: 6, recurrenceScore: 62,
          subtopics: ['Progressão Aritmética (PA - termo geral, soma)', 'Progressão Geométrica (PG - termo geral, soma)', 'Interpolação de termos', 'Aplicações em problemas contextualizados'] },
        { id: 'mat-09', name: 'Equação de 2º Grau', estHours: 2, weight: 5, recurrenceScore: 48,
          subtopics: ['Resolução (fórmula de Bhaskara, soma e produto)', 'Função quadrática (gráfico, vértice, raízes)', 'Valor máximo e mínimo', 'Inequações do 2º grau'] },
        { id: 'mat-10', name: 'Geometria Analítica', estHours: 2, weight: 3, recurrenceScore: 32,
          subtopics: ['Distância entre pontos', 'Equação da reta (geral, reduzida, segmentária)', 'Equação da circunferência', 'Posições relativas', 'Intersecção entre retas e círculos'] },
        { id: 'mat-11', name: 'Logaritmo', estHours: 3, weight: 5, recurrenceScore: 50,
          subtopics: ['Definição de logaritmo', 'Propriedades (produto, quociente, potência)', 'Mudança de base', 'Função logarítmica e exponencial', 'Equações e inequações logarítmicas', 'Aplicações (terremotos, pH, decibéis)'] },
        { id: 'mat-12', name: 'Trigonometria', estHours: 2, weight: 4, recurrenceScore: 42,
          subtopics: ['Razões trigonométricas (seno, cosseno, tangente)', 'Ciclo trigonométrico', 'Lei dos Senos e Cossenos', 'Funções trigonométricas (senoide, cossenoide)', 'Relações fundamentais'] },
        { id: 'mat-13', name: 'Conjuntos e Diagramas', estHours: 2, weight: 4, recurrenceScore: 42,
          subtopics: ['Operações com conjuntos (união, interseção, diferença)', 'Diagrama de Venn', 'Conjuntos numéricos (N, Z, Q, R)', 'Intervalos reais', 'Mapas conceituais e diagramas lógicos'] },
        { id: 'mat-14', name: 'Gráficos e Análise de Dados', estHours: 3, weight: 8, recurrenceScore: 88,
          subtopics: ['Leitura e interpretação de gráficos', 'Gráficos de setores, barras, linhas', 'Relação entre gráfico e função', 'Transformações em gráficos', 'Interpretação de informações visuais', 'Gráficos em meios de comunicação'] },
        { id: 'mat-15', name: 'Geometria Plana (Paralelogramos)', estHours: 2, weight: 4, recurrenceScore: 45,
          subtopics: ['Ângulos (opostos pelo vértice, complementares, suplementares)', 'Retas paralelas cortadas por transversal', 'Quadriláteros (paralelogramo, retângulo, losango, quadrado)', 'Propriedades e área', 'Teorema de Tales'] },
        { id: 'mat-16', name: 'Geometria Plana (Triângulos)', estHours: 3, weight: 6, recurrenceScore: 68,
          subtopics: ['Classificação (equilátero, isósceles, escaleno)', 'Pontos notáveis (baricentro, incentro, circuncentro, ortocentro)', 'Semelhança de triângulos (casos)', 'Teorema de Pitágoras', 'Relações métricas no triângulo retângulo', 'Trigonometria no triângulo retângulo'] },
        { id: 'mat-17', name: 'Círculo e Circunferência', estHours: 2, weight: 4, recurrenceScore: 42,
          subtopics: ['Elementos (raio, diâmetro, corda, arco)', 'Comprimento da circunferência', 'Área do círculo e setor circular', 'Ângulos na circunferência (central, inscrito)', 'Cilindro, cone e esfera'] },
        { id: 'mat-18', name: 'Geometria Espacial (Prismas e Pirâmides)', estHours: 3, weight: 5, recurrenceScore: 55,
          subtopics: ['Prismas (área lateral, área total, volume)', 'Pirâmides (área, volume, tronco)', 'Cubo e paralelepípedo', 'Relação de Euler', 'Planificação de sólidos'] },
        { id: 'mat-19', name: 'Geometria Espacial (Esferas e Cones)', estHours: 2, weight: 4, recurrenceScore: 42,
          subtopics: ['Cone reto (área, volume, tronco)', 'Esfera (área, volume, cunha)', 'Cilindro (área, volume)', 'Sólidos de revolução', 'Inscrição e circunscrição de sólidos'] },
        { id: 'mat-20', name: 'Análise Combinatória', estHours: 4, weight: 8, recurrenceScore: 85,
          subtopics: ['Princípio fundamental da contagem', 'Permutação simples e com repetição', 'Arranjo simples', 'Combinação simples', 'Permutação circular', 'Números binomiais e triângulo de Pascal', 'Probabilidade (espaço amostral, evento)'] },
        { id: 'mat-21', name: 'Probabilidade', estHours: 4, weight: 9, recurrenceScore: 92,
          subtopics: ['Conceito de probabilidade (clássica)', 'Probabilidade condicional', 'Eventos independentes e mutuamente exclusivos', 'Teorema de Bayes', 'Probabilidade da união e interseção', 'Distribuição binomial (experimentos de Bernoulli)', 'Valor esperado e esperança matemática'] },
        { id: 'mat-22', name: 'Matriz e Determinante', estHours: 2, weight: 4, recurrenceScore: 38,
          subtopics: ['Matrizes (soma, multiplicação, transposta, inversa)', 'Determinantes (cálculo 2x2, 3x3, propriedades)', 'Sistemas lineares por matrizes', 'Regra de Cramer'] }
      ]
    }
  ]
};

const ELO_THRESHOLDS = [
  { name: 'Ferro', min: 0, max: 40, icon: '🪨', color: '#8B7355' },
  { name: 'Bronze', min: 40, max: 60, icon: '🥉', color: '#CD7F32' },
  { name: 'Prata', min: 60, max: 75, icon: '🥈', color: '#A8A8A8' },
  { name: 'Ouro', min: 75, max: 90, icon: '🥇', color: '#FFD700' },
  { name: 'Desafiante', min: 90, max: 101, icon: '🏆', color: '#FF6B35' }
];
